// This file is generated by FlutterFire CLI.
// Run: dart pub global activate flutterfire_cli && flutterfire configure --project=YOUR_PROJECT_ID
// to generate the real version before running the app.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('Unsupported platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyyROYaVB3VgYYVJ3BF3y9GwjBO2yEUf0',
    appId: '1:980311061860:android:8753f989633645e267b671',
    messagingSenderId: '980311061860',
    projectId: 'minhainflacaoapp',
    storageBucket: 'minhainflacaoapp.firebasestorage.app',
  );

  // PLACEHOLDER: Replace with real values from Firebase Console

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByTUQMPt4cXRT0tzcwZokt533rUpVupjk',
    appId: '1:980311061860:ios:969d6527a64b4b3c67b671',
    messagingSenderId: '980311061860',
    projectId: 'minhainflacaoapp',
    storageBucket: 'minhainflacaoapp.firebasestorage.app',
    iosBundleId: 'br.com.minhainflacao.minhaInflacao',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI2ggHqAqTojHo2VqXuqiLt9UedklR-g8',
    appId: '1:980311061860:web:29346c2696baac9067b671',
    messagingSenderId: '980311061860',
    projectId: 'minhainflacaoapp',
    authDomain: 'minhainflacaoapp.firebaseapp.com',
    storageBucket: 'minhainflacaoapp.firebasestorage.app',
    measurementId: 'G-BY1XZP60Z5',
  );

}